version: '3.8'
services:
  mongodb:
    image: wmsolar/solardev:database
    container_name: mongodb
    volumes: 
      - type: volume
        source: mongodbdata
        target: /data/db
        volume:
          nocopy: true
    ports: 
      - "27017:27017"
    networks:
      - overlay

  api:
    build: .
    image: wmsolar/centosapiv1:latest
    container_name: apipoint
    networks:
      - overlay
    privileged: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/scr/app
    depends_on:
      - mongodb
       
volumes: 
  mongodbdata:
    external: true
    
networks:
   overlay:
