version: '3.8'
services:
  api:
    # image: wmsolar/solardev:latest
    build: .
    image: myapp
    networks:
      - overlay
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/scr/app
       
  web-cli:
    image: wmsolar/solardev:latest 
    # mongo-express:latest
    networks:
      - overlay
    command: sh
    depends_on:
      - mongodb
    
  mongodb:
    image: wmsolar/solardev:database
    container_name: mongodb
    volumes: 
      - type: volume
        source: mongodbdata
        target: /data/db
        volume:
          nocopy: true
    ports: 
      - "27017:27017"
    networks:
      - overlay
  
  test_api:
    image: myapp
    container_name: test_mocha
    command: dockerize
        -wait http://localhost:3000 10s
        bash -c "npm test"
    networks:
      - overlay
    volumes:
      - ./:/usr/src/app
    # restart: on-failure
    depends_on: 
      - api
      - mongodb
    
    

volumes: 
  mongodbdata:
    external: true
    
networks:
   overlay:

















# version: '3.8'
# services:
#   api:
#     image: mongo-express
#     build: .
#     networks:
#       - overlay
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./:/usr/src/app
#   web-cli:
#     image: mongo-express
#     networks:
#       - overlay
#     command: sh
#     depends_on:
#       - mongodb
    
#   mongodb:
#     image: blancoh2/mongo:latest
#     container_name: mongodb
#     volumes: 
#       - type: volume
#         source: mongodbdata
#         target: /data/db
#         volume:
#           nocopy: true
#     ports: 
#       - "27017:27017"
#     networks:
#       - overlay


# volumes: 
#   mongodbdata:

# networks:
#    overlay:

