version: '3.8'
services:
  mongodb:
    image: wmsolar/solardev:database
    container_name: mongodb
    volumes: 
      - type: volume
        source: mongodbdata
        target: /data/db
        volume:
          nocopy: true
    ports: 
      - "27017:27017"
    networks:
      - overlay

  api:
    build: .
    image: wmsolar/centosapiv1:latest
    container_name: apipoint
    # command: dockerize
    #     - wait /usr/sbin/sshd
    networks:
      - overlay
    privileged: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/scr/app
    depends_on:
      - mongodb
       
  # test_api:
  #   image: wmsolar/centosapiv1:latest
  #   container_name: test_mocha
    # command: dockerize
    #     - wait /usr/sbin/sshd
    #     - wait ssh root@apipoint "cd /usr/src/app && npm test"
    # networks:
    #   - overlay
   
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - ./:/usr/src/app
    # restart: on-failure
    # depends_on: 
    #   - api
    #   - mongodb

volumes: 
  mongodbdata:
    external: true
    
networks:
   overlay:
