image: wmsolar/solardev:mongoexps
image: wmsolar/mongo-express:latest
image: wmsolar/solardev:database

services:
  - docker:dind
cache:
  paths:
  - node_modules/

build:
  script:
   - docker-compose up -d
   - npm install
   - npm run test
