version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: wmsolar/solardev:mongoexps
    steps:
      - checkout
      - run:  
          name: Start container and verify
          command: |
            set -x
            docker image tag wmsolar/solardev:mongoexps mongo-express:latest
            docker-compose up -d
            docker container run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name centos7 -d mongo-express:latest

  
  # test:
  #   docker:
  #     - image: wmsolar/solardev:database
  #   steps:
  #     - checkout
  #     - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      # - test
      

  # run_tests:
  #   steps:  
  #     - run:
  #         name: run images
  #         command: |
  #            docker-compose up    
# workflows:
#   version: 2
#   build_test:
#     jobs:
#       - run_tests