version: 2
jobs:
  build:
    working_directory: /app
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Run tests
        command: |
              docker-compose -f ./docker-compose.yml up
